### ISSUE TITLE
A Strain on Reality - mistakes and typos (beware spoilers)

### ISSUE THREAD

**Issue by FASTNAVi** [scrubbless/PublishedScenarios#14] opened 2018-08-05 19:02 UTC
Hi @scrubbless ,

we just finnished your scenario. Thank you for your work! I will not write a feedback for BoardGameGeek now. I want to play it at least one more time before I will write it down. Anyway, you have 9/10 from us ;-)

We had 2 investigators, we won in 210 minutes.

1) We had 1 huge issue. After I used a UNDO button, the game was broken. The log was empty and I was unable to close it. I try undo two times.. luckily it was on start, so didn't ruin our long game but somebody can have a problem with it.. I really don't know where can be a problem hidden..

2) One game breaking issue. We found a green gem.. but in app we didn't see it.. and for example red gem was there as normal..

3) typo - when you go from bedroom on start, you have there "...space space..."
4) you have too many "wall" tokens.. just for your information..
5) from lounge you take more persons but you have there only "...person token..." instead tokens
6) we speek with Zadoc about Richard and we succeed.. you have "works" instead "words"
7) Zadoc about doctor Little.. you have "under go" instead of "undergo"
8) One of the mythos phases has a mistake. It starts with "The walls of this place..." and in the middle of the text you have "string" instead of "staring"
9) On door to office (after revelation) you have no "Cancel" button..
10) when you speak with doctor in lounge.. it seems some word is maybe missing there? Sorry, we don't remember what exactly..
11) we used a rift to library but app says "upstairs".. it was weird
12) also in rifts we noticed that bedroom is sometimes "bedroom" and sometimes "first floor bedroom"
13) we had a fire from mythos phase on the stairs.. but one round later we had a water from upstairs.. maybe you can add there information, that the waves of water can extinguish fire on stairs and lobby?
14) after killing a Orderly you have information about brass key "...in space as indicated." But it wasn't indicated.. maybe you mean in space of death of enemy or something...
15) you have somewhere "set of brass key". So, it is a set of brass key or one brass key? Add one "s" or delete set of ..
16) in Attic you have "place a search..." but it is a person token
17) I obtain two times in one game  a Pocket watch common item...... (first in lounge, second in closet)
18) enemy is Priest of DAGON, not DRAGON ;-)
19) you had a description of Star Spawn and you spawn a Star Spawn. But you write there "Spawn a Shoggoth"
20) after killing Priest of Dagon, "amulet rools on the floor" but we are outside, so ground?
21) on the end you have "...an end this madness..." probably missing "to" ?

So this is what we spot. We are looking forward for next play probably in Saturday. I will let you know again ;-)

One more time, your scenario is GREAT and we thank you so much for your work!!!

**Comment by scrubbless** [comment] 2018-08-05 19:26
Oh wow thank you for the feedback @FASTNAVi ! Detailed and concise! I'll work on routing them out. I hope the bugs didn't ruin it for you. I have been debugging this for months, but due to the sheer complexity it's hard to catch them all.

I hope you enjoy the second play through.

The undo button is that a serrate app? Can you let me know so I can try to simulate (or put a note not to use it :( ).

**Comment by FASTNAVi** [comment] 2018-08-05 19:37
No, it was not ruining the game.. we won so tightly.. I was one damage away from death and my wife had the same with horrors by the way :) Both insane, both wounded :D 

Yes, app was not working anymore. After that game I try it on my own scenario and there was UNDO working as normal. Try used UNDO in second or third round in your scenario and you will see..

And by the way, in my scenario under construction I have few very very similar ideas like you :D For example it is also a story in Asylum.. I am taking tiles from board too..... :)

**Comment by scrubbless** [comment] 2018-08-05 21:37
I wonder if the 'undo' didn't work because I have allot of empty events. I use them to set variables and there is a lot of randomisation. What is the undo? Is it part of Valkyrie or a separate program?

Also can you remember where you picked up the green gem? Their are 9 locations that the gems can spawn in and they are completely randomised!

If you can tell me what you searched it will help me fix it.

Empty chest in bedroom
Bathroom cabinets (victors belongings)
The book on the chair in library
Books in the office
Cook in kitchen
Infront of barrier
Box in lobby
Others necklace
Richards books

**Comment by scrubbless** [comment] 2018-08-06 10:28
> We had 1 huge issue. After I used a UNDO button, the game was broken. The log was empty and I was unable to close it. I try undo two times.. luckily it was on start, so didn't ruin our long game but somebody can have a problem with it.. I really don't know where can be a problem hidden..

I will have to test with the Undo application, however I was not aware it existed. I use a lot of loops and events with no dialogues to do calculations. So I suspect this will never work. My scenario is not coded in quite as sequentially as others. If you want to understand why, open it in the editor and run the events from the "START_GAME" event. You'll quickly see I use a lot of event loops :). I may just have to put a note in the clarifications that "UNDO" is not supported. But I will endeavour to support this in the next one :)

> One game breaking issue. We found a green gem.. but in app we didn't see it.. and for example red gem was there as normal..

I have asked about this one above, can you let me know the location you saw the green gem in, I can't track this down in the event chains from a quick look.

> typo - when you go from bedroom on start, you have there "...space space..."

Fixed, thanks!

> you have too many "wall" tokens.. just for your information..

You know what! I didn't count them. I have all the expansions so I believe more were added in one of them, maybe that's the problem. I'll see if I can remove some in non key area's.

> from lounge you take more persons but you have there only "...person token..." instead tokens

I am not sure what you mean here? Is it because I state "Place a Person token" instead of "Place the Richard Bechman token", I figured people could work this out. But I can change it if its confusing?

> we speek with Zadoc about Richard and we succeed.. you have "works" instead "words"

Fixed, thanks!

> Zadoc about doctor Little.. you have "under go" instead of "undergo"

Fixed, thanks!

> One of the mythos phases has a mistake. It starts with "The walls of this place..." and in the middle of the text you have "string" instead of "staring"

Fixed, thanks! These are the hardest to find, they don't show up in a spell check as they are words, just grammatical errors. The code in the localisation file makes it almost impossible to run a grammar check against it.

> On door to office (after revelation) you have no "Cancel" button..

There are two events there. When you don't have the key it only gives you the option to "Continue". When you have the key, it should give you the cancel option. 
I assume you mean when the Deep One Hybrid (Erics true form) spawns and you see where all the Patients are scattered around the building. The office will not let you interact with it until you have the silver key. That is intentional.

> when you speak with doctor in lounge.. it seems some word is maybe missing there? Sorry, we don't remember what exactly..

Every bit of evidence has a talking point when you run that event. The more evidence you have the more you 'scare' Doctor Little (so she spends more time clearing up her office instead of doing her ritual!) and the more time you have before the ritual completes (each adds 1 or 2 turns to the end game countdown). Its hard to make them flow, as not everyone will find every bit of evidence. 

> we used a rift to library but app says "upstairs".. it was weird

I'll take a look, I started off with very specific rift events, but then I decided to make them a bit more generic to reuse them. I may have missed some dialogues. It'll take me some time to catch all of these!

> also in rifts we noticed that bedroom is sometimes "bedroom" and sometimes "first floor bedroom"

I added "first floor" as I was worried to may be confused with the room the Investigators start in. I'll try to change these to keep them consistent.

> we had a fire from mythos phase on the stairs.. but one round later we had a water from upstairs.. maybe you can add there information, that the waves of water can extinguish fire on stairs and lobby?

Those events are very random, but I could set a flag in that event to say "stairs on fire". Then another event in the boat event to put out some of the fire. However it may confuse players that have already put out some of the fire in the stairs. 

Its a good call though, will be very cool to see that interaction.

> after killing a Orderly you have information about brass key "...in space as indicated." But it wasn't indicated.. maybe you mean in space of death of enemy or something...

Fixed , that should say in its space. I can't know what space the orderly will be standing in when he dies!

> you have somewhere "set of brass key". So, it is a set of brass key or one brass key? Add one "s" or delete set of ..

I've fixed that too, thanks!

> in Attic you have "place a search..." but it is a person token

> I obtain two times in one game a Pocket watch common item...... (first in lounge, second in closet)

There is a bug in Valkyrie where if you select multiple item categories, it can give you duplicates. I will hunt those down and fix the QItems. I have not had a chance to write an tiny scenario to reproduce the error to submit an issue (I did submit this before but Bruce couldn't reproduce it).


> enemy is Priest of DAGON, not DRAGON ;-)

Ahh Dragon!! Haha. Fixed! (that was my spell checker btw not me! Honest!)

> you had a description of Star Spawn and you spawn a Star Spawn. But you write there "Spawn a Shoggoth"

Fixed, it was originally a Shoggoth until I realized that it was not included in the base game :(
If you have SM or SoA there are two other possible boss battle locations and different monsters :D.

> after killing Priest of Dagon, "amulet rools on the floor" but we are outside, so ground?

Yeh good point, you don't always fight Dr Little outside, so must have been scripting an indoor location when I wrote that. Fixed.

> on the end you have "...an end this madness..." probably missing "to" ?

Yep, fixed!


Remember to update your downloaded copy before you play it Saturday :)

**Comment by FASTNAVi** [comment] 2018-08-06 16:33
ad2) We are sure, it was in library. Probably from talking with Richard?
ad5) No, I mean you are taking AWAY from board all the person tokens.. but instead of "tokens" you have there only "token"
ad9) Nope, I mean something else. One investigator enter an office and reveal it when Eric was away from lobby. Then second investigator try to enter too.. and you have possibility to click on "lobby" and "office" but not "cancel"..
ad10) I think you didn't understand me. We had one of conversation with her (hard to say which) and in the middle of the text was some GRAMMAR mistake.. some missing word. We forget to write it down, so we have no idea which exatcly was :-(
ad16) Just for sure, you fixed this too? I just that you have everywhere "fixed!" and here not :D 

Hope I am still helpful ;-)

**Comment by scrubbless** [comment] 2018-08-07 11:08
> ad2) We are sure, it was in library. Probably from talking with Richard?
It was in the Library, after picking up the book I think. I found it! It was really messing things up. Good catch, thank you! Fixed.

> ad5) No, I mean you are taking AWAY from board all the person tokens.. but instead of "tokens" you have there only "token"

I am not sure if I corrected this after I published the scenario (but before I read your post), but it now states (so Fixed?):
![image](https://user-images.githubusercontent.com/32058089/43772053-d87242a6-9a38-11e8-880b-b512572a0764.png)
![image](https://user-images.githubusercontent.com/32058089/43772061-e1e5e7d4-9a38-11e8-8727-5b99417341f3.png)

> ad9) Nope, I mean something else. One investigator enter an office and reveal it when Eric was away from lobby. Then second investigator try to enter too.. and you have possibility to click on "lobby" and "office" but not "cancel"..

I see what you mean. My thinking was that there was a cancel on the next button. But you're right, its a lot of clicks to get out of "just checking a button". Added a cancel, Fixed!

> ad10) I think you didn't understand me. We had one of conversation with her (hard to say which) and in the middle of the text was some GRAMMAR mistake.. some missing word. We forget to write it down, so we have no idea which exatcly was :-(

Thank you, I did re-read those dialogues and found a grammar mistake. Hopefully I got it! Fixed.

> ad16) Just for sure, you fixed this too? I just that you have everywhere "fixed!" and here not :D

Yes! Fixed!

> Hope I am still helpful ;-)

Its been extremely helpful, I appreciate you reaching out and answering these questions.

I have a couple more questions if you don't mind:

1) Did you use the journal much? Did it make sense? Did you like it?

2) Was the Ritual Book confusing, despite not having a GEM (from the bug) did you understand the puzzle? Was it too easy/too hard? Did you like it?

3) Did you have any problems with the secret door puzzle? What did you think of it? Did you like it?

**Comment by FASTNAVi** [comment] 2018-08-07 16:19
It is a reason why I want to wait before we will write a feedback on boardgamegeek.

ad1) just once.. yeah, it is nice how it works ;-)
ad2) we didn't a time to solve that at all
ad3) the same, we didn't a time to solve that (investigetor with Ritual components was too far from there)

**Comment by scrubbless** [comment] 2018-08-07 17:06
Did time run out before you got through the secret door? Ahh good to know. Will be interesting to see if I need to extend that phase for 2 investigators.

**Closed as completed** 2018-08-09 15:15 UTC

**Comment by scrubbless** [comment] 2018-08-13 15:42
I am quite sure that the Undo function does not work because the Save option in game also doesn't work. My gut is telling me there is a max file size or character limit that is corrupting the save file. Since the scenario is so massive.

I've opened an issue on the Valkyrie github.

**Comment by chrismaliszewski** [comment] 2018-12-27 23:24
Found minor mistakes:
TokenT1_PatientZadocNotMet.text: Should be 'The patient reading a newspaper seems calm and collected'; comma missing after 'Occasionally'
EventT8_EnterUpstairs_FromLobby.text: at the end, instead of 'an action' should be 'any action' to be correct, I think.
EventT1_ZadocPositive_Friends_NoInfo.text: lack of italics in the event when Zadok speaks.

Other than that, there are many commas missing. Should I look for them and list them for you?
